name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cuda=12.1
  - plyfile
  - python
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
